# What Justin Posey has said, confirmed, or leaned toward. No fan readings.
# tag: C = confirmed (official rules, his own posts, or a direct transcript quote)
#      S = said (in an interview or Q&A, reported by a named source)
#      L = leaned (a hedge, a soft yes/no, or a nudge in his own words)
#      D = declined (asked directly and would not answer; recorded so you know it is open)
SECTIONS = [
("The official rules", [
 ("C","Hunt Items (the treasure, the checkpoint and any placed clue) are NOT underwater, on private property, in caves, mines or tunnels, anywhere that needs rappelling, associated with man-made buildings, near graves or grave markers, or in dangerous places.","treasure.quest rules, Mar 2025"),
 ("C","All Hunt Items ARE more than one mile from anywhere Posey, his family or friends live, work or own property, including their businesses; on publicly accessible land anyone can visit; safe to get to.","treasure.quest rules, Mar 2025"),
 ("C","You do NOT need climbing gear or ropes, permission to enter private land, swimming skills, ladders or climbing skills, or a high-clearance vehicle.","treasure.quest rules, Mar 2025"),
 ("C","Railroad tracks: 'I consider them to be a man-made structure. Yes.' Then: 'Based on how the rules are described, railroad tracks are ruled out.'","Dillon Q&A, Jun 21 2025; Seekers Summit, Mar 28 2026"),
 ("C","'The treasure is not on private property.' Restated emphatically after reports of trespassing.","Posey, June 2026"),
 ("S","Federal versus state land: 'No, but it's publicly accessible as of today.' 'The focus is on legal accessibility of the final location, not convenience of access.'","Dillon Q&A, Jun 21 2025"),
 ("C","Do you have to pay to get in? 'No, not as of today.'","treasure.quest FAQ"),
 ("C","Can I bring my dog? 'If your dog is the outdoors type, absolutely!' The best way to use a dog in this hunt is to practice good outdoor manners, not to train it to sniff for gold.","treasure.quest FAQ; Dillon Q&A, Jun 21 2025 (1:17:09)"),
 ("S","Stay on public land. Use the available mapping apps to check property lines.","Dillon Q&A, Jun 21 2025 (35:00)"),
 ("S","Access to the location is free and available 24/7.","Posey Q&A (Mysterious Writings compilation)"),
 ("L","Is the hunt 24/7 accessible year round? 'I suppose that would depend on your definition of accessibility, but it would be possible.'","Seekers Summit Q&A transcript, Mar 28 2026 (1:07:25)"),
 ("S","'If you need rope then it's not the right location.' Searchers are going too deep into wilderness, rappelling into caves and searching cliffsides. Nothing dangerous is required.","Seekers Summit, Mar 28 2026"),
 ("S","A gazebo counts as a building. The exterior of a structure: 'always a possibility.' Can a hunt item be displayed on the outside of a man-made building? He does not want to limit that possibility. Not wheelchair accessible.","Seekers Summit, Mar 28 2026; X Marks the Pod, early 2026 (35:26)"),
 ("S","Are there loopholes in the rules? There are no intentional loopholes.","X Marks the Pod, early 2026 (34:11)"),
 ("D","Does the hunt require a river crossing? Not specified.","X Marks the Pod, early 2026 (50:23)"),
 ("S","No specialized knowledge is needed. No dangerous water crossings.","Public statements (research report)"),
 ("S","All clues are expected to stand the test of time; he will announce if something drastic changes.","Posey Q&A (MW compilation)"),
]),
("The poem: structure and how to read it", [
 ("C","All essential clues are in the poem, which is free on treasure.quest. Five stanzas of four lines. At least ten clues.","treasure.quest announcements"),
 ("C","The clues are in consecutive order, top to bottom.","treasure.quest FAQ and announcements"),
 ("C","No intentional red herrings in the poem or the book. No hidden codes in the website's source code.","Posey Q&A (MW compilation); Dillon Q&A, Jun 21 2025 (1:08:08)"),
 ("C","'I wrote the bulk of that poem in 6 hours or less. Purposely didn't finish the poem til the day the book went to print… I only tweaked two words tops.' Excluding a few minor tweaks, the poem stayed static from first draft to final.","Dillon Q&A, Jun 21 2025 (17:32)"),
 ("C","'Virtually every line in the poem is helpful. So just because as hope surges is the first actionable clue, doesn't mean people should discount the earlier lines. They are helpful context.'","X Dark Matters, Sep 4 2025"),
 ("C","The first actionable clue is 'As hope surges, clear and bright.' The last actionable clue: 'It does somewhat depend and depending on your interpretation it's either stanza four or five.'","Posey Q&A (MW compilation); Seekers Summit Q&A transcript, Mar 28 2026 (12:38)"),
 ("C","Does the poem need to be read or rearranged other than as presented? 'I'm not going to rule that out.'","Seekers Summit, Mar 28 2026"),
 ("C","Would a solver make more progress searching for hidden thematic or symbolic rules governing the poem, or by treating it more like Fenn's poem? 'Probably roughly both in equal measure.'","Seekers Summit Q&A transcript, Mar 28 2026 (23:07)"),
 ("C","Numbers are indirectly associated with the poem, hidden in words and wordplay: yes. Homophones and wordplay for numbers: 'Yes', kept in play. Anagrams: 'I haven't specified.'","Seekers Summit, Mar 28 2026"),
 ("S","There IS a distance element in following the clues.","Seekers Summit, Mar 28 2026"),
 ("C","Does timing matter, such as being at a spot at a specific time of day? 'That's an oddly specific question. What I will say is that the element of time, if it wasn't already obvious through the Netflix series, is important.'","Seekers Summit Q&A transcript, Mar 28 2026 (2:34)"),
 ("C","Is there a time-travel element to the hunt? 'Not to my knowledge.'","Seekers Summit Q&A transcript, Mar 28 2026 (1:08:05)"),
 ("C","Anything to clarify about the structure logic of the poem? 'There's nothing that I'm aware of that needs clarification right now.'","Seekers Summit Q&A transcript, Mar 28 2026 (1:18:47)"),
 ("C","Is there a question he is shocked no one has asked? 'I can think of one very specific question that would be extremely useful to ask… I can't verbalize it though.'","Seekers Summit Q&A transcript, Mar 28 2026 (1:19:07)"),
 ("C","Is the poem an instruction manual, a map, or both? 'In a way, a map can be an instruction manual, so I guess, yeah.'","Sandal Sanders livestream, Sep 2025"),
 ("S","'From beginning to end of the poem… it will inherently create some sort of shape.'","Interview, 2025 (JIBLE index)"),
 ("C","Are transitions between clues movement across meaningful geographic separation, or conceptual steps within the same area? 'Each clue in the poem is not meant to convey great distance.'","Seekers Summit Q&A transcript, Mar 28 2026 (19:14)"),
 ("L","Asked whether the poem is linear, several points miles apart, or a hybrid, he declined, then offered: 'there are some great movies out there: Indiana Jones and National Treasure.'","Posey Q&A, 2025"),
 ("S","Backtracking: 'If you knew the entirety of the solution, then the answer is no. But if you go through the natural progression, the answer is more like a yes.'","X Q&A via Mysterious Writings, Sep 2025"),
 ("C","There are multiple valid ways to solve it: 'in case certain aspects of the mechanics don't work… there are other ways to approach it so that you end up finding it either way.' 'There is an optimal solution and fallback paths… someone might not quite understand one clue, they could still limp along.'","Sandal livestream, Sep 27 2025; Dillon, Jun 2025"),
 ("C","How verifiable is a solve? Between Sudoku and 'jump in the lake': 'a reasonable person would say okay, seems reasonable.'","Seekers Summit, Mar 28 2026"),
 ("S","Asked for the distance from the first actionable clue to the treasure: 'just by virtue of going through the process of formulating that question, you might find the answer.'","X Q&A via Mysterious Writings, Sep 2025"),
 ("S","'How far from the first clue to the last in miles' is impossible to answer given how the clues are structured.","Posey Q&A (MW compilation)"),
 ("C","Are there multiple meanings to 'castle'? 'Only one correct interpretation.'","Seekers Summit, Mar 28 2026"),
 ("C","Is 'bride' the right word? 'No. I'm pretty pleased with that one.'","Seekers Summit, Mar 28 2026"),
 ("D","Whether 'cast your pole' refers to a fishing pole: not specified.","Posey Q&A (MW compilation)"),
 ("D","Whether the poem references Native American legends, or contains golf references: not specified.","Posey Q&A (MW compilation)"),
]),
("Solving from home, boots on the ground, and distances", [
 ("S","A 'fair amount' can be solved from home. Boots on the ground are required for retrieval.","Posey Q&A (MW compilation)"),
 ("C","At which stanza does boots on the ground become absolutely required, with no at-home research able to substitute? 'Stanza four.'","Seekers Summit Q&A transcript, Mar 28 2026 (8:00)"),
 ("C","'If you've solved the poem in its entirety, you'll end up at an exact location.'","treasure.quest FAQ"),
 ("S","It is walking distance from 'waters' silent flight' through 'round the bend, past the Hole.'","Posey Q&A (MW compilation)"),
 ("C","How far from your car? 'You don't need to hike a great distance. You don't need to hike more than a mile to figure out where the treasure is at.'","treasure.quest FAQ"),
 ("S","'On earth, in the American West, not a place you have to go many miles to find.'","Seekers Summit, Mar 28 2026"),
 ("C","'If you're needing to drink many bottles of water, you're going too far.'","Seekers Summit, Mar 28 2026"),
 ("S","A hike is required to reach the treasure location. He declined to specify its length.","Dillon Q&A, Jun 21 2025 (1:18:50)"),
 ("C","'Even a serious low rider would absolutely have made it' on the BLM dirt roads.","Seekers Summit, Mar 28 2026"),
 ("S","'By the time you're going to get the treasure you're not searching, you're retrieving.' Once you know exactly where it is you will have time to plan the retrieval.","X Marks the Pod, Sep 4 2025"),
 ("S","No grid searching.","X Marks the Pod, early 2026"),
]),
("The site itself", [
 ("C","Does anybody besides him know where the treasure is? 'No, there is not a soul that knows but me. I am the only person on the planet.'","Treasure Hunt With Us, Apr 9 2025 (0:38)"),
 ("C","'A place that is important to me, and a place that I've known about for quite some time.' Meaningful for beauty, symbolism AND sentiment: 'all of the above.'","Seekers Summit, Mar 28 2026"),
 ("S","'In a place that's dear to my heart' and 'surrounded by significance.'","Public statements (research report)"),
 ("C","Physical objects along the way: 'fair to say there are.'","Seekers Summit, Mar 28 2026"),
 ("C","Will the finder have come to know the site's personal lore and secrets? 'I think so.'","Seekers Summit, Mar 28 2026"),
 ("C","Is there a significant clue visible standing 15 feet from the container? 'The most accurate answer is no.'","Seekers Summit, Mar 28 2026"),
 ("S","'I did not put it in very close proximity to any man-made trail… so it is a little ways off.' He did not want a random hiker to stumble on it.","Dillon Q&A, Jun 21 2025"),
 ("S","The entire hunt is based on naturally occurring structures and landscapes. Depending which solution path you take, one clue has a man-made implication. 'One clue arguably has a man-made implication, but the whole hunt could be solved using only natural structures depending on interpretation.'","Dillon Q&A, Jun 21 2025"),
 ("C","Do you need to move a rock or anything else to see the container, and would a flashlight help during the day? 'Something will need to be manipulated in order to see the treasure.' Depending on conditions, a flashlight could be helpful.","Seekers Summit Q&A transcript, Mar 28 2026 (18:03); Posey Q&A (MW compilation)"),
 ("C","Is it buried? 'If you know where to go, it wouldn't matter either way.' He will not say whether it is buried because AI could use it.","treasure.quest FAQ; X Marks the Pod"),
 ("L","Digging: 'not something I'm willing to rule out.' Metal detector: 'probably not.'","Seekers Summit, Mar 28 2026"),
 ("D","Do you need to move any rocks? 'I am going to punt on that one.'","Seekers Summit Q&A transcript, Mar 28 2026 (42:19)"),
 ("C","Do you need to get your feet wet to obtain the treasure? 'You don't have to.'","Seekers Summit Q&A transcript, Mar 28 2026 (1:07:47)"),
 ("C","Something along the way 'will help significantly' (said on X Marks the Pod in the context of trinkets). Asked to elaborate: 'It's pivotal to your journey.'","Seekers Summit Q&A transcript, Mar 28 2026 (39:54)"),
 ("L","Do I need a wizard staff during any part of the hunt? 'Every journey needs a good walking stick.'","Seekers Summit Q&A transcript, Mar 28 2026 (1:17:50)"),
 ("C","'There is a vantage point involved. But it's not that any of the clues are necessarily talking about that vantage point.' (Asked about the vantage point in his grandfather's memoir.)","Seekers Summit, Mar 28 2026"),
 ("S","The treasure is located at an elevation below 11,000 feet.","Dillon Q&A, Jun 21 2025 (1:01:55)"),
 ("S","Clues may cross state lines. Not in a pay park, national-park fee area or restricted zone.","Posey, per the treasurehuntamusementpark research hub (secondary)"),
 ("S","He did not create a physical 'blaze' on a tree. He wanted his markers to stand the test of time against natural forces.","Dillon Q&A, Jun 21 2025 (21:34)"),
 ("D","Are national parks ruled out? 'I'm not going to say yes or no to that.'","Seekers Summit Q&A transcript, Mar 28 2026 (31:17)"),
 ("D","Whether the site predates his Fenn searches: not specified.","Posey Q&A (MW compilation)"),
 ("D","Can a Prius get within a mile of the treasure? He chose to punt.","Livestream interview transcript (timestamped; matches the Sandal Sanders livestream, Sep 2025) (29:43)"),
]),
("The Hole and the double arcs", [
 ("S","The Hole carries no man-made implication: a direct 'no.'","Seekers Summit, Mar 28 2026"),
 ("D","Does the Hole correspond to a place with 'hole' in its name (Jackson Hole, Big Hole River)? 'An on the nose question.' Not answered.","Seekers Summit, Mar 28 2026"),
 ("D","Is 'double arcs on granite bold' the clue with the man-made implication? Punted.","Dillon Q&A, Jun 21 2025"),
 ("D","Do the arcs exist naturally or were they created? 'A strange question to answer since he knows what he knows.' Not answered.","Dillon Q&A, Jun 21 2025"),
 ("D","Is 'double arcs' a directional bearing? Punted.","Seekers Summit, Mar 28 2026"),
]),
("Stanza 3: ursa, he, the bride, the gates, her face", [
 ("C","Is 'east' a portion within one Ursa, or is there a west Ursa and an east Ursa? 'You only need to worry about Ursa East.'","Seekers Summit, Mar 28 2026"),
 ("C","Is 'ursa' lowercase deliberately? The poem was written deliberately; the choice not to capitalize was intentional. On 'use a star': 'that's all the clarity I'm willing to provide.'","Seekers Summit, Mar 28 2026"),
 ("S","Is 'he' living, or was he ever living? 'That depends on your perspective.'","Seekers Summit, Mar 28 2026"),
 ("S","The bride is not a person who is alive right now. He does not want anyone thinking she is a living person you can interact with, so that searchers do not hassle real people. The bride is something visible.","Seekers Summit, Mar 28 2026"),
 ("S","Is the bride alive? Declined to answer in June 2025. By September: 'Depends on how you define the term alive.'","Dillon Q&A, Jun 21 2025 (1:20:55); Sandal livestream, Sep 2025"),
 ("C","Has anyone located or correctly identified the bride? 'Yes.'","Seekers Summit Q&A transcript, Mar 28 2026 (1:34)"),
 ("S","It would be 'a little strange' to discover the bride without understanding the ancient gates.","Seekers Summit, Mar 28 2026"),
 ("C","Does her face belong to the bride? Yes (after hedging about two interpretations). Is 'return her face' referring to the bride? Punted in Sep 2025, answered yes at the Summit.","X Dark Matters, Sep 2025; Seekers Summit, Mar 28 2026"),
 ("S","Does 'return her face' imply a physical rotation? 'The technically correct answer is yes.'","Seekers Summit, Mar 28 2026"),
 ("C","How far is 'her face' from 'the place'? 'Probably not as far as many people might think.'","Seekers Summit, Mar 28 2026"),
 ("C","How far is the treasure from the bride? 'A matter of perspective.'","Seekers Summit, Mar 28 2026"),
 ("C","Do you need to be at the bride to identify her foot of three? He stalled, re-read the line, then answered: No.","Seekers Summit, Mar 28 2026"),
 ("C","Are 'the place' (3:4) and 'the sacred space' (4:4) the same location? 'Not necessarily.'","Seekers Summit, Mar 28 2026"),
 ("D","Is the place in her face or her gaze? No clarity given.","Seekers Summit, Mar 28 2026"),
]),
("The checkpoint", [
 ("S","There is a built-in checkpoint. It gives the reassuring feeling you are not lost and 'zero doubt' you are trending right. You are at least halfway through the poem's clues when you reach it. It is part of the poem, a stage of the journey. Excellent chance you find the treasure if you are first to it.","Posey Q&A (MW compilation)"),
 ("S","The checkpoint is both something he placed AND something already there. Tied to a topographic feature? 'There is some implication there.' Not something you need to worry about moving. It is possible to be at it and not recognize it, depending how close you are.","Seekers Summit, Mar 28 2026"),
 ("S","'You'd be hard pressed to get all the way without seeing the checkpoint.' 'There is a chance you could bypass it, but boy the odds are astronomically low.'","Posey Q&A; X Q&A via MW, Sep 2025"),
 ("C","The checkpoint is not visible in the Netflix series.","Posey on X, Aug 1 2025"),
 ("D","Is the checkpoint a boots-on-the-ground checkpoint or a before-you-go checkpoint? 'I haven't specified, but I might reconsider that in the future. For now, I have to avoid answering.'","Treasure Hunt With Us, Apr 9 2025 (2:56)"),
 ("C","How does he know a searcher was near the checkpoint? 'I'm not going to say the exact way, but there are a number of ways that people have conveyed to me where they're searching. In one of those spheres, I have come to learn that there have been more than one person that have been close to the checkpoint.'","Seekers Summit Q&A transcript, Mar 28 2026 (32:40)"),
 ("D","Can he view searchers if they are near the treasure? 'I am going to punt on that question.'","Seekers Summit Q&A transcript, Mar 28 2026 (15:05)"),
 ("C","Has any searcher been in the small kitchen-sized area where the treasure is hidden? 'To my uncertain knowledge, no.'","Seekers Summit Q&A transcript, Mar 28 2026 (14:26)"),
 ("S","'Zero doubt': the clues are designed so that a searcher's confidence in the path increases as they progress rather than stagnating.","Toby Younis interview (A Gypsy's Kiss) (6:56)"),
 ("C","'Formalized hide-and-seek with confidence checkpoints. I wanted to give a way for people to gain confidence as opposed to losing confidence as they work through clues.'","X Marks the Pod, early 2026"),
]),
("Where it is and is not", [
 ("S","June 2025: he was not ruling out any search state, including Montana, but might consider it in the future if there was no tangible progress.","Dillon Q&A, Jun 21 2025 (19:12)"),
 ("S","Colorado and Oregon are eliminated, per the Mysterious Writings account of the Summit. Note: in the Q&A transcript, asked 'What are the two states you would have eliminated?' (23:45) he declined to name them and redirected.","Seekers Summit via Mysterious Writings; Seekers Summit Q&A transcript, Mar 28 2026 (23:45)"),
 ("C","What does eliminating a state mean? 'When I say eliminate a state, I mean that you don't need to worry about it. Like there are no clues in that state. There's no treasure in that state. It's complete elimination.'","Seekers Summit Q&A transcript, Mar 28 2026 (36:17)"),
 ("S","Are the majority of the hunt items and locations in the same state or county as the treasure? 'I would just generally be less concerned about the borders.'","Seekers Summit Q&A transcript, Mar 28 2026 (10:42)"),
 ("L","Do the states chosen for the Summit events have anything to do with where the treasure is? 'I'm certainly not going to rule them out.'","Seekers Summit Q&A transcript, Mar 28 2026 (1:09:13)"),
 ("S","'The treasure is absolutely hidden somewhere on the map that I've published.' The map is useful, 'for a couple different reasons.'","Posey Q&A; X Marks the Pod"),
 ("S","'I chose the landmarks to be labeled, but the map was designed by a third party. Any incorrect names, positions, and elevations are not intentional.'","Posey (quoted in research)"),
 ("S","The website map's missing state capital and misspellings are accidental.","Public statements (research report)"),
 ("S","Is the site within 75 miles of somewhere he searched for the Fenn chest? 'I searched a lot of places, guys. Uh, so yeah, I mean it's true to say that at some point I had searched for the Fenn treasure within that 75 mile radius. Yeah.' He then walked it back, not wanting people to think he had eliminated states, and said his early idea of the Rocky Mountains was 'incredibly broad, any mountain with rocks.'","Seekers Summit, Mar 28 2026"),
 ("S","During his Fenn search he believes he was extremely close to the chest in Yellowstone, possibly within 10 to 15 feet, and missed it.","Public statements (research report)"),
 ("C","Seeing the animal while hiding gave him no fear: 'It was quite the opposite.'","Seekers Summit Q&A transcript, Mar 28 2026 (38:34)"),
 ("C","An animal seen while hiding: mammalian, NOT a moose, the first time he had seen it in nature. 'If I said the animal it could have a pretty profound impact on the search area.' Separately he has said he has seen a wolverine in the wild.","Seekers Summit, Mar 28 2026"),
]),
("The book, the map, the logo, the dedication", [
 ("C","The Netflix hints 'guide you in the book.'","Dillon Q&A, Jun 21 2025"),
 ("C","'It is true to say that layer five has some bearing on the treasure hunt.' Not defined further.","Seekers Summit, Mar 28 2026"),
 ("C","The ankh in the legal section is not a clue. 'The Legal Lowdown' has no hints.","Seekers Summit, Mar 28 2026"),
 ("C","The dedication is 'layered and intentional… I am talking about a person… someone very special.'","Seekers Summit, Mar 28 2026"),
 ("C","The rancher 'Niven': 'an interesting character, that's about all I can say.'","Seekers Summit, Mar 28 2026"),
 ("C","The logo: 'the angzarr symbol. I chose and modified it intentionally.' 'I designed the logo intentionally and it has some meaning.'","X Dark Matters, Sep 4 2025; X Marks the Pod"),
 ("S","Are 'The Goonies' or 'A River Runs Through It' helpful? Fun for 'pregaming' an adventure, but not strictly necessary for the hunt.","Livestream interview transcript (timestamped; matches the Sandal Sanders livestream, Sep 2025) (27:08)"),
 ("S","'Take your treasure hat off and read the memoir as a memoir.' 'Understanding the person who hid it is the clearest map.'","X Marks the Pod, early 2026"),
 ("C","The one mistake searchers consistently make, and the reset: 'Take a Matt stance, Matt the editor. If you're getting in deep and you feel like you're going down many rabbit holes, probably the best reset is to just read it as a memoir.'","Seekers Summit Q&A transcript, Mar 28 2026 (58:18)"),
 ("C","Does the book mention the area of the first actionable clue? 'The very specific area is not mentioned, but there are times in the book where descriptions pertain to the area where the treasure is hidden.'","Seekers Summit Q&A transcript, Mar 28 2026 (1:23:39)"),
 ("C","How many hints or clues are in the book's stories, not counting the poem? 'I haven't counted them but there are several.'","Seekers Summit Q&A transcript, Mar 28 2026 (1:06:08)"),
 ("C","He did not plan to write a book at first; he wrote it so everyone was on equal footing and to have creative control over hints. Not every story has a hint, but they are sprinkled throughout.","Treasure Hunt With Us, Apr 9 2025 (3:47)"),
 ("C","His favorite story in the book: he has 'an affinity for the postal pilgrimage.'","Treasure Hunt With Us, Apr 9 2025 (5:01)"),
 ("S","The book his uncle Hyram gave him is 'Early Spanish Signs and Symbols.'","Dillon Q&A, Jun 21 2025 (24:43)"),
 ("S","The ebook's pictures are black and white to keep the file size compatible with e-readers.","Dillon Q&A, Jun 21 2025 (1:16:08)"),
 ("S","Strategy advice: watch the series, read the book, and read the poem multiple times.","Dillon Q&A, Jun 21 2025 (30:46)"),
 ("L","Do the four points of the compass designate a specific site? 'Anything related to that, the book is the best reference.' Asked whether they map to the starting point, Wisdom, the bride, the brother, the babbling brook, the grandfather and the exact spot: 'a good question, but I have to punt on that.'","Treasure Hunt With Us, Apr 9 2025 (14:03, 14:46)"),
 ("C","Were any of the photographs in the book (not illustrations) placed to function as explicit clues? 'I think they are useful. Yes.'","Seekers Summit Q&A transcript, Mar 28 2026 (11:34)"),
 ("C","Are there any clues in the Tucker poem? 'I think a reasonable person would say that that poem is helpful.'","Seekers Summit Q&A transcript, Mar 28 2026 (43:16)"),
 ("C","Is the map still useful once you have made tangible progress? 'I think it's a good primer.'","Seekers Summit Q&A transcript, Mar 28 2026 (1:18:21)"),
 ("C","Discrepancies between the hardcover and the audiobook or ebook (Big Hill, Doc's death, mileage, age) are not intentional. 'I did publish an errata on treasure.quest. The purpose is to make sure people don't spend time on things that don't matter that were truly just mistakes.'","Seekers Summit Q&A transcript, Mar 28 2026 (46:35)"),
 ("C","Is the number 42 relevant to finding the treasure? 'I guess the short answer is yes.' On 42: 'The Hitchhiker's Guide to the Galaxy is a fantastic book.' Asked about the 42 on his taillight, he gave no more.","Seekers Summit, Mar 28 2026; X Marks the Pod"),
]),
("The cipher, the technical hint, the songs", [
 ("S","One cipher exists, plus one hint he describes as 'somewhat technical.' Neither is critical to the solution. Earlier: 'There are two elements. One is a cipher (very approachable), and the other might require technical know-how, but there are ways to uncover it without advanced knowledge. It is not a super critical clue.'","Seekers Summit, Mar 28 2026; Treasure Hunt With Us, Apr 9 2025 (19:24)"),
 ("D","Is the cipher more toward the poem or the book? 'I haven't specified.' (A year later: 'Who says the cipher is in the book?')","Treasure Hunt With Us, Apr 9 2025 (20:47)"),
 ("S","Is the cipher in one section of the book or several? 'Who says the cipher is in the book?'","Seekers Summit, Mar 28 2026"),
 ("C","The cipher's answer is MAGYAR, solved April 2026 and confirmed. Basic math only. 'The cipher is more than anything a nod to what the container is.' MAGYAR does not give coordinates, a state or a region.","Posey, April 2026; Sandal livestream"),
 ("C","'The key to one direction lies in another' is a hidden audio message in the ARKADE song. He confirmed it as the technical clue, not as the core geographic solution. Does it relate to the azimuth? 'No.'","Posey, April 2026; Seekers Summit"),
 ("C","Are the clocks part of the cipher? 'Yes.'","Seekers Summit Q&A transcript, Mar 28 2026 (38:08)"),
 ("S","There are clues in the hunt's songs. One song contains what he called an extremely definitive clue.","Posey Q&A (MW compilation); Livestream interview transcript (timestamped; matches the Sandal Sanders livestream, Sep 2025) (43:40)"),
 ("S","Is the cipher solvable without a math degree? Yes, it is designed to be approachable.","Livestream interview transcript (timestamped; matches the Sandal Sanders livestream, Sep 2025) (38:12)"),
 ("S","One person has solved the technical clue; it is not required to find the treasure. He was surprised it took so long: it is an Easter egg he never intended as a core barrier to entry.","Livestream interview transcript (matches the Sandal Sanders livestream, Sep 2025) (38:56); Toby Younis interview (A Gypsy's Kiss) (24:06)"),
 ("L","Can the poem be solved with a flow equation? That 'sounds like it would require an advanced degree.'","Livestream interview transcript (timestamped; matches the Sandal Sanders livestream, Sep 2025) (57:08)"),
]),
("The Netflix series", [
 ("S","He had no creative control and did not know scene order, framing or focus. He hid hints during filming that even the producers did not know about. Clues exist only 'where I had some notion of control, directly or indirectly.'","Posey Q&A; Dillon Q&A"),
 ("C","At least five singular clues, plus compound clues that need several scenes.","Dillon Q&A, Jun 21 2025"),
 ("C","Two 'super obvious' hints: 'It's either episode two or three. It is a scene that does not have me in it. But it was a scene that I had some control over. If you rewatch it, it'll be pretty obvious.' By Sep 27 2025 he said people had figured these out.","Dillon Q&A, Jun 21 2025; Sandal livestream"),
 ("C","The lawyer / Carl scene: zero clues.","Dillon Q&A, Jun 21 2025"),
 ("C","The Red Mountain clip was B-roll chosen by the crew: 'I didn't have any influence or involvement in that.'","Seekers Summit Q&A transcript, Mar 28 2026 (1:05:00)"),
 ("C","Is all the footage he wanted in Gold & Greed actually in it? 'Everything that I really wanted to be included got included.'","Seekers Summit Q&A transcript, Mar 28 2026 (1:08:20)"),
 ("C","The clock: Roman numerals make no difference. Clock count: 'the lower the number the better.' Times 4:02 and 5:26 are eliminated as meaningful.","Dillon Q&A; Posey Q&A (MW compilation)"),
 ("S","Was the clock actually moving during filming? 'That might have been a little uncanny.' (The research hub records him calling 4:19 on the clock 'a little uncanny.')","Treasure Hunt With Us, Apr 9 2025 (11:22); research hub (secondary)"),
]),
("The container and the treasure", [
 ("C","'Who says it's a box?' The container is an existing object with 'targeted and deliberate modifications.' Some searchers have guessed it correctly. 'Extremely recognizable. Anybody who watched the series or read my book will know right away.' Not a Fenn replica. No knowledge of the Fenn hunt is needed.","Treasure Hunt With Us, Apr 9 2025; treasure.quest FAQ"),
 ("C","The Tucker bronze statue is NOT the treasure. The original Saddleback briefcase that carried the treasure, plus the Netflix coffee mugs, ship to the winner.","Treasure Hunt With Us, Apr 9 2025"),
 ("C","The whole treasure weighs about 60 pounds including the container.","treasure.quest FAQ"),
 ("S","The treasure is a real, physical collection of gold and gems located in the wilderness, not a proxy item.","Dillon Q&A, Jun 21 2025 (23:27)"),
 ("S","He will not reveal what the container is, to prevent decoys and because of possible future interference by AI.","Dillon Q&A, Jun 21 2025 (13:05)"),
 ("S","To claim the prize, the finder uses the email address on page 150 of the signed books. The prize includes the original Saddleback leather briefcase and the coffee mugs.","Dillon Q&A, Jun 21 2025 (1:13:24)"),
 ("S","Contents: mostly gold (bars, flakes, dust), precious gems, rare coins across eras, a meteorite, historical artifacts dating to 561 BC, items from the Forrest Fenn chest including the dragon bracelet, and a Bitcoin wallet funded by book sales. A separate Steward holds additional items.","Posey Q&A; public statements"),
 ("S","The 1652 Oak Tree shilling in the treasure has a personal backstory: it replaced a counterfeit one from his grandfather's collection.","X Marks the Pod, early 2026 (30:18)"),
 ("S","The steward verifies the finder's authenticity, releases the remaining Bitcoin wallet key, and ensures no one continues searching after the find.","Toby Younis interview (A Gypsy's Kiss) (31:49)"),
 ("S","Finders keepers. The finder may remain anonymous but must come forward within 30 days to claim the Bitcoin portion. The 30-day requirement protects the finder: there is additional legal paperwork on file with the steward that is important for the finder to have. The complete solution will be revealed at the conclusion of the hunt, with supporting documentation, to give 'zero doubt' that the treasure was hidden where claimed.","Posey Q&A (MW compilation); Treasure Hunt With Us, Apr 9 2025 (9:10); Toby Younis interview (A Gypsy's Kiss) (34:39)"),
 ("C","When the treasure is found, will he post a 30-day countdown on the website? 'Yes, I think I will. I think that's only fair.'","Treasure Hunt With Us, Apr 9 2025 (6:46)"),
]),
("The hiding trip", [
 ("C","Two journeys in 2023 totaling more than 9,000 miles; the first was reconnaissance. Off-grid. 'No hint meant to be read into 9,000 miles.' The point of the statement was to convey that he traveled a great distance.","Seekers Summit, Mar 28 2026; Dillon Q&A, Jun 21 2025 (10:49)"),
 ("C","At least four trips from the car, all within a 24-hour span, with a broken tibia, not in his own vehicle.","Seekers Summit, Mar 28 2026"),
 ("C","'Anonymous travel is very hard… my route was convoluted… I did it twice.' He has never returned and has no plans to.","Seekers Summit, Mar 28 2026"),
 ("S","He aimed to leave no digital footprint of the journey, and filmed the description of the treasure for Netflix only just before release so production staff had no advantage.","Public statements (research report)"),
]),
("Progress reports, in date order", [
 ("C","Mar 28 2025: 'The treasure has NOT been found!'","Posey on X"),
 ("S","Jun 21 2025: people have been within two miles, 'and certainly even less.' To his knowledge nobody had reached the checkpoint, and nobody had mentioned the correct answer to the cipher.","Dillon Q&A, Jun 21 2025 (7:39)"),
 ("C","Aug 1 2025: several searchers have solved at least the first two clues; some have been within 200 feet of the checkpoint; zero searchers have sent a photo of the correct checkpoint.","Posey on X"),
 ("C","Sep 2025: stanza 1 and 'at least PART of stanza 2' solved (the interview version said 'at least half of it'). Searchers are 'quite close.' Searchers do not know without doubt until the checkpoint.","Posey on X; X Marks the Pod"),
 ("C","Mar 28 2026: part of stanza 3 solved; 'at least six clues' by the most advanced searcher; the kitchen-sized target area unreached; 'No group way off in left field. No group uber close.' 'Tangible progress… absolutely attainable… a matter of time.'","Seekers Summit"),
 ("C","Summit statistics: 277,428 verify requests; 119,644 people '100% sure'; 1,221 bribe attempts; 80 blackmail attempts; 19 tracking attempts; 16 search-and-rescue operations.","Seekers Summit, Mar 28 2026"),
 ("S","Jul 2026: the separate marked-book prize was found, 'not the treasure (yet).'","Posey, July 2026"),
 ("S","He estimates 10,000 to 100,000 active searchers, from emails, social media and bookstore visits. Searchers who do not post publicly often email him.","Toby Younis interview (A Gypsy's Kiss) (46:12, 42:25)"),
 ("S","Since July 2026 he answers a monthly Featured Question through Mysterious Writings. Questions phrased specifically but not 'on the nose' have gotten real answers.","Mysterious Writings"),
 ("C","Pep talk: 'The night is darkest before the light. If you are confident in the location in which you're searching, I see little reason to stray.'","X Marks the Pod, early 2026"),
]),
("Design philosophy, in his words", [
 ("C","'The part of me that embraces childlike wonder' wrote the poem.","X Marks the Pod, early 2026 (5:39)"),
 ("S","treasure.quest is the 'single source of truth': official guidance lives there, so participants do not need social media or private Discord channels. He plans to move into a bystander role with no further media appearances.","Toby Younis interview (A Gypsy's Kiss) (11:36); Froggy interview, 2025 (24:06)"),
 ("S","Open book on the narrative, steel vault on the mechanics: mechanical details require careful crafting, so he prefers written responses over off-the-cuff verbal ones to avoid errors.","Toby Younis interview (A Gypsy's Kiss) (15:42)"),
 ("S","He treated Fenn's hunt as a case study and used hindsight to build guardrails for a smoother, verifiable, streamlined experience. Success means independent, verifiable findings and few post-find conspiracy theories.","Toby Younis interview (A Gypsy's Kiss) (5:08, 8:36)"),
 ("S","Has his level of interaction made the hunt harder or more confusing? Off-the-cuff responses in forums can sometimes muddy the waters, though his intent is to provide clarity.","X Marks the Pod, early 2026 (3:31)"),
 ("S","Anything to clarify or take back from other interviews? He is happy with the status quo and fears further clarification might create more ambiguity.","X Marks the Pod, early 2026 (5:08)"),
 ("S","Are Google Earth and AI helping or hurting? Both. Some people see patterns in foliage that do not exist.","X Marks the Pod, early 2026 (6:36)"),
 ("C","Designed for humans, not AI: 'creating a puzzle for an intellect that dwarfs our own is a paradox… I really wanted to design something that embraces the core of what it means to be human… an astronomical amount of thought.' He will not divulge the tactics.","X Q&A via MW, Sep 2025; X Marks the Pod"),
 ("S","Difficulty: somewhere in the middle on a scale of one to Forrest Fenn.","Dillon Q&A, Jun 21 2025 (42:57)"),
 ("C","Disney Imagineering background (about a decade): 'not just you go and get it. There's something more to it.' Tiers: 'some easier things… and some more challenging.' He wanted it approachable yet challenging, not impossible: a mix of easier and harder clues.","X Marks the Pod, early 2026; Froggy interview, 2025 (1:43)"),
 ("C","'Forrest spent like 10 years… I came up with the bulk of that poem in about four to six hours.' Asked whether he is prouder of the spot or the puzzle: equally pleased with both.","Froggy interview, 2025 (21:43, 22:49)"),
]),
("About Justin, as he has stated it", [
 ("C","He is married.","Livestream interview transcript (timestamped; matches the Sandal Sanders livestream, Sep 2025) (58:17)"),
 ("S","Why public lands matter to him: rooted in childhood experiences, and younger generations need to connect with nature.","Livestream interview transcript (timestamped; matches the Sandal Sanders livestream, Sep 2025) (8:04)"),
 ("S","His best experience of the hunt: seeing families find the inspiration to share an adventure together.","Livestream interview transcript (timestamped; matches the Sandal Sanders livestream, Sep 2025) (17:16)"),
 ("S","He still has his grandmother's sweater but chooses not to wear it, to preserve its 'mystique.'","Livestream interview transcript (timestamped; matches the Sandal Sanders livestream, Sep 2025) (24:09)"),
 ("S","He studied computer science but did not graduate, and worked at Microsoft, the Walt Disney Company and Visa.","Dillon Q&A, Jun 21 2025 (51:59)"),
 ("S","His biggest fish: a very large trout caught trolling at Heron Lake, New Mexico, which made the local newspapers.","Dillon Q&A, Jun 21 2025 (45:45)"),
 ("S","He hunted for Forrest Fenn's treasure for ten years. He enjoys creating his own hunt because he can build in everything he wished other hunts had.","Froggy interview, 2025 (0:15)"),
 ("S","His grandfather Wayne, the game warden, survived a Jeep accident because someone happened to notice tire tracks leading off the road.","Froggy interview, 2025 (17:28)"),
 ("S","He sold his truck, 'The Beast,' after Tucker died; it was too painful to drive.","Froggy interview, 2025 (8:06)"),
 ("S","He gets violently seasick, so he prefers inland trout fishing to offshore fishing. He still subconsciously checks mile markers while driving.","Froggy interview, 2025 (12:30, 10:21)"),
 ("S","The Victorio Peak mystery captured his heart as a youth and still interests him; he has theorized about using radar and bat colonies to find alternate cave entrances. As a child in Tucson he hid things for himself to find, and had a pet raccoon named Rascal.","Froggy interview, 2025 (4:26, 3:12, 8:54)"),
 ("S","He had considered creating a hunt for years, inspired by Forrest Fenn's. Serious health concerns were the turning point. He went in 'eyes wide open' about lawsuits and chaos, driven by the joy he felt in past hunts.","Toby Younis interview (A Gypsy's Kiss) (2:38, 3:52)"),
 ("S","Raised in Arizona, based in Texas. Software engineer, art and antiques dealer. Searched for the Fenn chest for years; bought the Fenn chest from the finder, auctioned most of its contents in Dec 2022, and kept the chest, the dragon bracelet, some coins, dust and flakes.","Public statements (research report)"),
 ("S","His grandfather was a fish-and-game warden in Montana; Justin spent summers at the family cabin exploring the hills with a metal detector. His grandfather wrote memoirs; Justin's favorite story is the poacher confronted at a cabin poker game.","Seekers Summit; public statements"),
 ("C","Bringing Tucker to Nine Mile Hole during the Fenn search was risky: a dog crossing the river there would have been conspicuous, and it was a dangerous endeavor. He does not regret bringing Tucker to the hunt.","Treasure Hunt With Us, Apr 9 2025 (7:58)"),
 ("C","The first time Brandon joined him searching for Fenn's treasure was in Yellowstone, at Iron Springs.","Seekers Summit Q&A transcript, Mar 28 2026 (50:13)"),
 ("C","On seekers trying to find Brandon's memorial in Tucson: 'You don't need to take any big risks here.'","Seekers Summit Q&A transcript, Mar 28 2026 (55:51)"),
 ("C","Favorite childhood memory with Brandon: building forts; Brandon building a bench, sitting on it, and it falling over. What it comes down to is 'the resilience that he had even at a very young age. He was a very stubborn kid.'","Seekers Summit Q&A transcript, Mar 28 2026 (1:00:01)"),
 ("C","Questions he would ask a seeker: 'Understanding the creator and their intent is important. It's not really a question you should ask, but a theme.'","Seekers Summit Q&A transcript, Mar 28 2026 (1:21:14)"),
 ("S","The hunt is dedicated to four departed loved ones: his father, his grandfather, his brother Brandon, and his dog Tucker. Tucker was a Vizsla, a Hungarian breed (which is what MAGYAR nods to).","Book dedication; Posey, April 2026"),
]),
]
