# What Justin Posey has said, confirmed, or leaned toward. No fan readings.
# tag: C = confirmed (official rules, his own posts, or a direct transcript quote)
#      S = said (in an interview or Q&A, reported by a named source)
#      L = leaned (a hedge, a soft yes/no, or a nudge in his own words)
#      D = declined (asked directly and would not answer; recorded so you know it is open)
SECTIONS = [
("The official rules", [
 ("C","Hunt Items (the treasure, the checkpoint and any placed clue) are NOT underwater, on private property, in caves, mines or tunnels, anywhere that needs rappelling, associated with man-made buildings, near graves or grave markers, or in dangerous places.","treasure.quest rules, Mar 2025"),
 ("C","All Hunt Items ARE more than one mile from anywhere Posey, his family or friends live, work or own property, including their businesses; on publicly accessible land anyone can visit; safe to get to.","treasure.quest rules, Mar 2025"),
 ("C","You do NOT need climbing gear or ropes, permission to enter private land, swimming skills, ladders or climbing skills, or a high-clearance vehicle.","treasure.quest rules, Mar 2025"),
 ("C","Railroad tracks: 'I consider them to be a man-made structure. Yes.' Then: 'Based on how the rules are described, railroad tracks are ruled out.'","Dillon Q&A, Jun 21 2025; Seekers Summit, Mar 28 2026"),
 ("C","'The treasure is not on private property.' Restated emphatically after reports of trespassing.","Posey, June 2026"),
 ("S","Federal versus state land: 'No, but it's publicly accessible as of today.' 'The focus is on legal accessibility of the final location, not convenience of access.'","Dillon Q&A, Jun 21 2025"),
 ("C","Do you have to pay to get in? 'No, not as of today.'","treasure.quest FAQ"),
 ("C","Can I bring my dog? 'If your dog is the outdoors type, absolutely!'","treasure.quest FAQ"),
 ("S","Access to the location is free and available 24/7.","Posey Q&A (Mysterious Writings compilation)"),
 ("S","'If you need rope then it's not the right location.' Searchers are going too deep into wilderness, rappelling into caves and searching cliffsides. Nothing dangerous is required.","Seekers Summit, Mar 28 2026"),
 ("S","A gazebo counts as a building. The exterior of a structure: 'always a possibility.' Not wheelchair accessible.","Seekers Summit, Mar 28 2026"),
 ("S","No specialized knowledge is needed. No dangerous water crossings.","Public statements (research report)"),
 ("S","All clues are expected to stand the test of time; he will announce if something drastic changes.","Posey Q&A (MW compilation)"),
]),
("The poem: structure and how to read it", [
 ("C","All essential clues are in the poem, which is free on treasure.quest. Five stanzas of four lines. At least ten clues.","treasure.quest announcements"),
 ("C","The clues are in consecutive order, top to bottom.","treasure.quest FAQ and announcements"),
 ("C","No red herrings in the poem. No hidden codes in the website's source code.","Posey Q&A (MW compilation)"),
 ("C","'I wrote the bulk of that poem in 6 hours or less. Purposely didn't finish the poem til the day the book went to print… I only tweaked two words tops.'","Dillon Q&A, Jun 21 2025"),
 ("C","'Virtually every line in the poem is helpful. So just because as hope surges is the first actionable clue, doesn't mean people should discount the earlier lines. They are helpful context.'","X Dark Matters, Sep 4 2025"),
 ("S","The first actionable clue is 'As hope surges, clear and bright.' The last actionable clue is in stanza four or five, depending on interpretation.","Posey Q&A (MW compilation)"),
 ("C","Does the poem need to be read or rearranged other than as presented? 'I'm not going to rule that out.'","Seekers Summit, Mar 28 2026"),
 ("C","Thematic or literal? 'Probably roughly both in equal measure.'","Seekers Summit, Mar 28 2026"),
 ("C","Numbers are indirectly associated with the poem, hidden in words and wordplay: yes. Homophones and wordplay for numbers: 'Yes', kept in play. Anagrams: 'I haven't specified.'","Seekers Summit, Mar 28 2026"),
 ("S","There IS a distance element in following the clues.","Seekers Summit, Mar 28 2026"),
 ("C","Is the poem an instruction manual, a map, or both? 'In a way, a map can be an instruction manual, so I guess, yeah.'","Sandal Sanders livestream, Sep 2025"),
 ("S","'From beginning to end of the poem… it will inherently create some sort of shape.'","Interview, 2025 (JIBLE index)"),
 ("S","Each clue is not meant to convey great distance.","Seekers Summit, Mar 28 2026"),
 ("L","Asked whether the poem is linear, several points miles apart, or a hybrid, he declined, then offered: 'there are some great movies out there: Indiana Jones and National Treasure.'","Posey Q&A, 2025"),
 ("S","Backtracking: 'If you knew the entirety of the solution, then the answer is no. But if you go through the natural progression, the answer is more like a yes.'","X Q&A via Mysterious Writings, Sep 2025"),
 ("C","There are multiple valid ways to solve it: 'in case certain aspects of the mechanics don't work… there are other ways to approach it so that you end up finding it either way.' 'There is an optimal solution and fallback paths… someone might not quite understand one clue, they could still limp along.'","Sandal livestream, Sep 27 2025; Dillon, Jun 2025"),
 ("C","How verifiable is a solve? Between Sudoku and 'jump in the lake': 'a reasonable person would say okay, seems reasonable.'","Seekers Summit, Mar 28 2026"),
 ("S","Asked for the distance from the first actionable clue to the treasure: 'just by virtue of going through the process of formulating that question, you might find the answer.'","X Q&A via Mysterious Writings, Sep 2025"),
 ("S","'How far from the first clue to the last in miles' is impossible to answer given how the clues are structured.","Posey Q&A (MW compilation)"),
 ("C","Are there multiple meanings to 'castle'? 'Only one correct interpretation.'","Seekers Summit, Mar 28 2026"),
 ("C","Is 'bride' the right word? 'No. I'm pretty pleased with that one.'","Seekers Summit, Mar 28 2026"),
 ("D","Whether 'cast your pole' refers to a fishing pole: not specified.","Posey Q&A (MW compilation)"),
 ("D","Whether the poem references Native American legends, or contains golf references: not specified.","Posey Q&A (MW compilation)"),
]),
("Solving from home, boots on the ground, and distances", [
 ("S","A 'fair amount' can be solved from home. Boots on the ground are required for retrieval.","Posey Q&A (MW compilation)"),
 ("S","Boots on the ground becomes absolutely required at stanza four.","Posey Q&A (MW compilation)"),
 ("C","'If you've solved the poem in its entirety, you'll end up at an exact location.'","treasure.quest FAQ"),
 ("S","It is walking distance from 'waters' silent flight' through 'round the bend, past the Hole.'","Posey Q&A (MW compilation)"),
 ("C","How far from your car? 'You don't need to hike a great distance. You don't need to hike more than a mile to figure out where the treasure is at.'","treasure.quest FAQ"),
 ("S","'On earth, in the American West, not a place you have to go many miles to find.'","Seekers Summit, Mar 28 2026"),
 ("C","'If you're needing to drink many bottles of water, you're going too far.'","Seekers Summit, Mar 28 2026"),
 ("C","'Even a serious low rider would absolutely have made it' on the BLM dirt roads.","Seekers Summit, Mar 28 2026"),
 ("S","'By the time you're going to get the treasure you're not searching, you're retrieving.' Once you know exactly where it is you will have time to plan the retrieval.","X Marks the Pod, Sep 4 2025"),
 ("S","No grid searching.","X Marks the Pod, early 2026"),
]),
("The site itself", [
 ("C","'A place that is important to me, and a place that I've known about for quite some time.' Meaningful for beauty, symbolism AND sentiment: 'all of the above.'","Seekers Summit, Mar 28 2026"),
 ("S","'In a place that's dear to my heart' and 'surrounded by significance.'","Public statements (research report)"),
 ("C","Physical objects along the way: 'fair to say there are.'","Seekers Summit, Mar 28 2026"),
 ("C","Will the finder have come to know the site's personal lore and secrets? 'I think so.'","Seekers Summit, Mar 28 2026"),
 ("C","Is there a significant clue visible standing 15 feet from the container? 'The most accurate answer is no.'","Seekers Summit, Mar 28 2026"),
 ("S","'I did not put it in very close proximity to any man-made trail… so it is a little ways off.' He did not want a random hiker to stumble on it.","Dillon Q&A, Jun 21 2025"),
 ("S","The entire hunt is based on naturally occurring structures and landscapes. Depending which solution path you take, one clue has a man-made implication. 'One clue arguably has a man-made implication, but the whole hunt could be solved using only natural structures depending on interpretation.'","Dillon Q&A, Jun 21 2025"),
 ("S","Something will need to be manipulated in order to see the treasure. Depending on conditions, a flashlight could be helpful.","Posey Q&A (MW compilation)"),
 ("C","Is it buried? 'If you know where to go, it wouldn't matter either way.' He will not say whether it is buried because AI could use it.","treasure.quest FAQ; X Marks the Pod"),
 ("L","Digging: 'not something I'm willing to rule out.' Metal detector: 'probably not.'","Seekers Summit, Mar 28 2026"),
 ("D","Whether you need to move any rocks: punted.","Posey Q&A (MW compilation)"),
 ("C","'There is a vantage point involved. But it's not that any of the clues are necessarily talking about that vantage point.' (Asked about the vantage point in his grandfather's memoir.)","Seekers Summit, Mar 28 2026"),
 ("S","The site is below 11,000 feet. Clues may cross state lines. Not in a pay park, national-park fee area or restricted zone.","Posey, per the treasurehuntamusementpark research hub (secondary)"),
 ("D","Whether national parks are ruled out: will not say yes or no.","Posey Q&A (MW compilation)"),
 ("D","Whether the site predates his Fenn searches: not specified.","Posey Q&A (MW compilation)"),
]),
("The Hole and the double arcs", [
 ("S","The Hole carries no man-made implication: a direct 'no.'","Seekers Summit, Mar 28 2026"),
 ("D","Does the Hole correspond to a place with 'hole' in its name (Jackson Hole, Big Hole River)? 'An on the nose question.' Not answered.","Seekers Summit, Mar 28 2026"),
 ("D","Is 'double arcs on granite bold' the clue with the man-made implication? Punted.","Dillon Q&A, Jun 21 2025"),
 ("D","Do the arcs exist naturally or were they created? 'A strange question to answer since he knows what he knows.' Not answered.","Dillon Q&A, Jun 21 2025"),
 ("D","Is 'double arcs' a directional bearing? Punted.","Seekers Summit, Mar 28 2026"),
]),
("Stanza 3: ursa, he, the bride, the gates, her face", [
 ("C","Is 'east' a portion within one Ursa, or is there a west Ursa and an east Ursa? 'You only need to worry about Ursa East.'","Seekers Summit, Mar 28 2026"),
 ("C","Is 'ursa' lowercase deliberately? The poem was written deliberately; the choice not to capitalize was intentional. On 'use a star': 'that's all the clarity I'm willing to provide.'","Seekers Summit, Mar 28 2026"),
 ("S","Is 'he' living, or was he ever living? 'That depends on your perspective.'","Seekers Summit, Mar 28 2026"),
 ("S","The bride is not a person who is alive right now. He does not want anyone thinking she is a living person you can interact with, so that searchers do not hassle real people. The bride is something visible.","Seekers Summit, Mar 28 2026"),
 ("S","Has the bride ever been alive? 'Depends on how you define the term alive.'","Sandal livestream, Sep 2025"),
 ("S","Someone has correctly identified the bride.","Seekers Summit, Mar 28 2026"),
 ("S","It would be 'a little strange' to discover the bride without understanding the ancient gates.","Seekers Summit, Mar 28 2026"),
 ("C","Does her face belong to the bride? Yes (after hedging about two interpretations). Is 'return her face' referring to the bride? Punted in Sep 2025, answered yes at the Summit.","X Dark Matters, Sep 2025; Seekers Summit, Mar 28 2026"),
 ("S","Does 'return her face' imply a physical rotation? 'The technically correct answer is yes.'","Seekers Summit, Mar 28 2026"),
 ("C","How far is 'her face' from 'the place'? 'Probably not as far as many people might think.'","Seekers Summit, Mar 28 2026"),
 ("C","How far is the treasure from the bride? 'A matter of perspective.'","Seekers Summit, Mar 28 2026"),
 ("C","Do you need to be at the bride to identify her foot of three? He stalled, re-read the line, then answered: No.","Seekers Summit, Mar 28 2026"),
 ("C","Are 'the place' (3:4) and 'the sacred space' (4:4) the same location? 'Not necessarily.'","Seekers Summit, Mar 28 2026"),
 ("D","Is the place in her face or her gaze? No clarity given.","Seekers Summit, Mar 28 2026"),
]),
("The checkpoint", [
 ("S","There is a built-in checkpoint. It gives the reassuring feeling you are not lost and 'zero doubt' you are trending right. You are at least halfway through the poem's clues when you reach it. It is part of the poem, a stage of the journey. Excellent chance you find the treasure if you are first to it.","Posey Q&A (MW compilation)"),
 ("S","The checkpoint is both something he placed AND something already there. Tied to a topographic feature? 'There is some implication there.' Not something you need to worry about moving. It is possible to be at it and not recognize it, depending how close you are.","Seekers Summit, Mar 28 2026"),
 ("S","'You'd be hard pressed to get all the way without seeing the checkpoint.' 'There is a chance you could bypass it, but boy the odds are astronomically low.'","Posey Q&A; X Q&A via MW, Sep 2025"),
 ("C","The checkpoint is not visible in the Netflix series.","Posey on X, Aug 1 2025"),
 ("C","'Formalized hide-and-seek with confidence checkpoints. I wanted to give a way for people to gain confidence as opposed to losing confidence as they work through clues.'","X Marks the Pod, early 2026"),
]),
("Where it is and is not", [
 ("S","Colorado is eliminated. Oregon is eliminated. Both intentional.","Seekers Summit, Mar 28 2026"),
 ("S","'The treasure is absolutely hidden somewhere on the map that I've published.' The map is useful, 'for a couple different reasons.'","Posey Q&A; X Marks the Pod"),
 ("S","'I chose the landmarks to be labeled, but the map was designed by a third party. Any incorrect names, positions, and elevations are not intentional.'","Posey (quoted in research)"),
 ("S","The website map's missing state capital and misspellings are accidental.","Public statements (research report)"),
 ("S","Is the site within 75 miles of somewhere he searched for the Fenn chest? 'I searched a lot of places, guys. Uh, so yeah, I mean it's true to say that at some point I had searched for the Fenn treasure within that 75 mile radius. Yeah.' He then walked it back, not wanting people to think he had eliminated states, and said his early idea of the Rocky Mountains was 'incredibly broad, any mountain with rocks.'","Seekers Summit, Mar 28 2026"),
 ("S","During his Fenn search he believes he was extremely close to the chest in Yellowstone, possibly within 10 to 15 feet, and missed it.","Public statements (research report)"),
 ("C","An animal seen while hiding: mammalian, NOT a moose, the first time he had seen it in nature. 'If I said the animal it could have a pretty profound impact on the search area.' Separately he has said he has seen a wolverine in the wild.","Seekers Summit, Mar 28 2026"),
]),
("The book, the map, the logo, the dedication", [
 ("C","The Netflix hints 'guide you in the book.'","Dillon Q&A, Jun 21 2025"),
 ("C","'It is true to say that layer five has some bearing on the treasure hunt.' Not defined further.","Seekers Summit, Mar 28 2026"),
 ("C","The ankh in the legal section is not a clue. 'The Legal Lowdown' has no hints.","Seekers Summit, Mar 28 2026"),
 ("C","The dedication is 'layered and intentional… I am talking about a person… someone very special.'","Seekers Summit, Mar 28 2026"),
 ("C","The rancher 'Niven': 'an interesting character, that's about all I can say.'","Seekers Summit, Mar 28 2026"),
 ("C","The logo: 'the angzarr symbol. I chose and modified it intentionally.' 'I designed the logo intentionally and it has some meaning.'","X Dark Matters, Sep 4 2025; X Marks the Pod"),
 ("S","'Take your treasure hat off and read the memoir as a memoir.' 'Understanding the person who hid it is the clearest map.'","X Marks the Pod, early 2026"),
 ("C","The number 42 is relevant. On 42: 'The Hitchhiker's Guide to the Galaxy is a fantastic book.' Asked about the 42 on his taillight, he gave no more.","Seekers Summit, Mar 28 2026; X Marks the Pod"),
]),
("The cipher, the technical hint, the songs", [
 ("S","One cipher exists, plus one hint he describes as 'somewhat technical.' Neither is critical to the solution.","Seekers Summit, Mar 28 2026"),
 ("S","Is the cipher in one section of the book or several? 'Who says the cipher is in the book?'","Seekers Summit, Mar 28 2026"),
 ("C","The cipher's answer is MAGYAR, solved April 2026 and confirmed. Basic math only. 'The cipher is more than anything a nod to what the container is.' MAGYAR does not give coordinates, a state or a region.","Posey, April 2026; Sandal livestream"),
 ("C","'The key to one direction lies in another' is a hidden audio message in the ARKADE song. He confirmed it as the technical clue, not as the core geographic solution. Does it relate to the azimuth? 'No.'","Posey, April 2026; Seekers Summit"),
 ("S","There are clues in the hunt's songs. One song contains what he called an extremely definitive clue.","Posey Q&A (MW compilation)"),
]),
("The Netflix series", [
 ("S","He had no creative control and did not know scene order, framing or focus. He hid hints during filming that even the producers did not know about. Clues exist only 'where I had some notion of control, directly or indirectly.'","Posey Q&A; Dillon Q&A"),
 ("C","At least five singular clues, plus compound clues that need several scenes.","Dillon Q&A, Jun 21 2025"),
 ("C","Two 'super obvious' hints: 'It's either episode two or three. It is a scene that does not have me in it. But it was a scene that I had some control over. If you rewatch it, it'll be pretty obvious.' By Sep 27 2025 he said people had figured these out.","Dillon Q&A, Jun 21 2025; Sandal livestream"),
 ("C","The lawyer / Carl scene: zero clues.","Dillon Q&A, Jun 21 2025"),
 ("C","The clock: Roman numerals make no difference. Clock count: 'the lower the number the better.' Times 4:02 and 5:26 are eliminated as meaningful.","Dillon Q&A; Posey Q&A (MW compilation)"),
 ("S","The clocks are relevant; he called 4:19 on the Netflix clock 'a little uncanny.'","Posey, per the research hub (secondary)"),
]),
("The container and the treasure", [
 ("C","'Who says it's a box?' The container is an existing object with 'targeted and deliberate modifications.' Some searchers have guessed it correctly. 'Extremely recognizable. Anybody who watched the series or read my book will know right away.' Not a Fenn replica. No knowledge of the Fenn hunt is needed.","Treasure Hunt With Us, Apr 9 2025; treasure.quest FAQ"),
 ("C","The Tucker bronze statue is NOT the treasure. The original Saddleback briefcase that carried the treasure, plus the Netflix coffee mugs, ship to the winner.","Treasure Hunt With Us, Apr 9 2025"),
 ("C","The whole treasure weighs about 60 pounds including the container.","treasure.quest FAQ"),
 ("S","Contents: mostly gold (bars, flakes, dust), precious gems, rare coins across eras, a meteorite, historical artifacts dating to 561 BC, items from the Forrest Fenn chest including the dragon bracelet, and a Bitcoin wallet funded by book sales. A separate Steward holds additional items.","Posey Q&A; public statements"),
 ("S","Finders keepers. The finder may remain anonymous but must come forward within 30 days to claim the Bitcoin portion. The complete solution will be revealed at the conclusion of the hunt.","Posey Q&A (MW compilation)"),
]),
("The hiding trip", [
 ("C","Two journeys in 2023 totaling more than 9,000 miles; the first was reconnaissance. Off-grid. 'No hint meant to be read into 9,000 miles.'","Seekers Summit, Mar 28 2026"),
 ("C","At least four trips from the car, all within a 24-hour span, with a broken tibia, not in his own vehicle.","Seekers Summit, Mar 28 2026"),
 ("C","'Anonymous travel is very hard… my route was convoluted… I did it twice.' He has never returned and has no plans to.","Seekers Summit, Mar 28 2026"),
 ("S","He aimed to leave no digital footprint of the journey, and filmed the description of the treasure for Netflix only just before release so production staff had no advantage.","Public statements (research report)"),
]),
("Progress reports, in date order", [
 ("C","Mar 28 2025: 'The treasure has NOT been found!'","Posey on X"),
 ("S","Jun 21 2025: people have been within two miles, 'and certainly even less.'","Dillon Q&A"),
 ("C","Aug 1 2025: several searchers have solved at least the first two clues; some have been within 200 feet of the checkpoint; zero searchers have sent a photo of the correct checkpoint.","Posey on X"),
 ("C","Sep 2025: stanza 1 and 'at least PART of stanza 2' solved (the interview version said 'at least half of it'). Searchers are 'quite close.' Searchers do not know without doubt until the checkpoint.","Posey on X; X Marks the Pod"),
 ("C","Mar 28 2026: part of stanza 3 solved; 'at least six clues' by the most advanced searcher; the kitchen-sized target area unreached; 'No group way off in left field. No group uber close.' 'Tangible progress… absolutely attainable… a matter of time.'","Seekers Summit"),
 ("C","Summit statistics: 277,428 verify requests; 119,644 people '100% sure'; 1,221 bribe attempts; 80 blackmail attempts; 19 tracking attempts; 16 search-and-rescue operations.","Seekers Summit, Mar 28 2026"),
 ("S","Jul 2026: the separate marked-book prize was found, 'not the treasure (yet).'","Posey, July 2026"),
 ("S","Since July 2026 he answers a monthly Featured Question through Mysterious Writings. Questions phrased specifically but not 'on the nose' have gotten real answers.","Mysterious Writings"),
 ("C","Pep talk: 'The night is darkest before the light. If you are confident in the location in which you're searching, I see little reason to stray.'","X Marks the Pod, early 2026"),
]),
("Design philosophy, in his words", [
 ("C","'The part of me that embraces childlike wonder' wrote the poem.","X Marks the Pod, early 2026"),
 ("C","Designed for humans, not AI: 'creating a puzzle for an intellect that dwarfs our own is a paradox… I really wanted to design something that embraces the core of what it means to be human… an astronomical amount of thought.' He will not divulge the tactics.","X Q&A via MW, Sep 2025; X Marks the Pod"),
 ("C","Disney Imagineering background (about a decade): 'not just you go and get it. There's something more to it.' Tiers: 'some easier things… and some more challenging.'","X Marks the Pod, early 2026"),
 ("C","'Forrest spent like 10 years… I came up with the bulk of that poem in about four to six hours.'","Froggy interview, 2025"),
]),
("About Justin, as he has stated it", [
 ("S","Raised in Arizona, based in Texas. Software engineer, art and antiques dealer. Searched for the Fenn chest for years; bought the Fenn chest from the finder, auctioned most of its contents in Dec 2022, and kept the chest, the dragon bracelet, some coins, dust and flakes.","Public statements (research report)"),
 ("S","His grandfather was a fish-and-game warden in Montana; Justin spent summers at the family cabin exploring the hills with a metal detector. His grandfather wrote memoirs; Justin's favorite story is the poacher confronted at a cabin poker game.","Seekers Summit; public statements"),
 ("S","The hunt is dedicated to four departed loved ones: his father, his grandfather, his brother Brandon, and his dog Tucker. Tucker was a Vizsla, a Hungarian breed (which is what MAGYAR nods to).","Book dedication; Posey, April 2026"),
]),
]
